ChurchApps/MembershipApi

tools/dbScripts/people.mysql
Make sure to recreate people table on staging and production
=> Set gender column data length to 11 varchar (people table)

src/controllers/PersonController.ts, src/helpers/Permissions.ts
https://github.com/LiveChurchSolutions/MembershipApi/issues/8
=> allow people with 'Edit Self' permission to update their people record

src/controllers/ChurchController.ts, src/controllers/PersonController.ts, src/repositories/PersonRepository.ts, tools/dbScripts/people.mysql
https://github.com/LiveChurchSolutions/AccessApi/issues/48
=> refactor: remove userId from people table and update the rest of the code

src/controllers/ChurchController.ts
This change should make everything run as it was. This fix is need cause of https://github.com/LiveChurchSolutions/AccessApi/issues/46
=> refactor: /churches/init api

src/controllers/AnswerController.ts, src/controllers/FormController.ts, src/controllers/FormSubmissionController.ts, src/controllers/QuestionController.ts, src/controllers/index.ts, src/models/Answer.ts, src/models/Form.ts, src/models/FormSubmission.ts, src/models/Question.ts, src/models/index.ts, src/repositories/AnswerRepository.ts, src/repositories/FormRepository.ts, src/repositories/FormSubmissionRepository.ts, src/repositories/QuestionRepository.ts, src/repositories/Repositories.ts, src/repositories/index.ts
Moving the Form, FormSubmission, Question, and Answer model/repo/controller from the baseApi to the membershipApi.
=> Move forms to membership api

src/controllers/UserController.ts, src/repositories/RoleMemberRepository.ts, src/repositories/RolePermissionRepository.ts, src/repositories/UserChurchRepository.ts, src/repositories/UserRepository.ts
Backend changes for https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/86
=> add delete user api

src/controllers/FormSubmissionController.ts, src/models/Person.ts, src/repositories/FormRepository.ts, src/repositories/MemberPermissionRepository.ts, src/repositories/PersonRepository.ts
resolved: https://github.com/LiveChurchSolutions/ChurchAppsSupport/issues/147
=> feat: send email to form members

src/controllers/PersonController.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/206
=> add: search route to person based on groupId

src/repositories/GroupMemberRepository.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/244
=> improve: only load active groups for group members

src/controllers/UserChurchController.ts, src/repositories/UserChurchRepository.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/257
=> add route to delete church from userChurches

src/controllers/QuestionController.ts, src/repositories/QuestionRepository.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/252
=> improve: questions sort

src/helpers/ChurchHelper.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/284
=> improve: remove non-alphanumeric chrac from subdomain

src/controllers/RoleMemberController.ts, src/repositories/RoleMemberRepository.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/279
=> allow rolemembers to remove themselves from church

src/controllers/GroupController.ts, src/repositories/GroupRepository.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/339
=> improve: remove teams when deleting a ministry

src/repositories/PersonRepository.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/380
=> improve: ignore spaces when checking phone number

src/models/Group.ts, src/repositories/GroupRepository.ts, tools/dbScripts/groups.mysql
https://github.com/ChurchApps/ChurchAppsSupport/issues/270
=> add: printNametag to groups

src/controllers/FormSubmissionController.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/449
=> fix: change church name in form emails

src/controllers/VisibilityPreferenceController.ts, src/controllers/index.ts, src/models/VisibilityPreference.ts, src/models/index.ts, src/repositories/Repositories.ts, src/repositories/VisibilityPreferenceRepository.ts, src/repositories/index.ts, tools/dbScripts/visibilityPreferences.mysql
https://github.com/ChurchApps/ChurchAppsSupport/issues/442
=> add: visibility preference

src/controllers/DomainController.ts, src/controllers/FormController.ts, src/controllers/FormSubmissionController.ts, src/controllers/GroupController.ts, src/controllers/GroupMemberController.ts, src/controllers/HouseholdController.ts, src/controllers/MemberPermissionController.ts, src/controllers/PersonController.ts, src/controllers/QuestionController.ts, src/controllers/UserChurchController.ts, src/controllers/UserController.ts
Related Issue:  #511
Changes:
- added a return statement to all delete methods to send a JSON response after deleting entries/data
=> feat: updated all DELETE method and return a response #511

src/controllers/PersonController.ts, src/repositories/PersonRepository.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/444
=> filter person info based on visibility preferences

src/models/Form.ts, src/repositories/FormRepository.ts, src/repositories/GroupMemberRepository.ts, src/repositories/GroupRepository.ts, tools/dbScripts/accessLogs.mysql, tools/dbScripts/answers.mysql, tools/dbScripts/churches.mysql, tools/dbScripts/clientErrors.mysql, tools/dbScripts/domains.mysql, tools/dbScripts/formSubmissions.mysql, tools/dbScripts/forms.mysql, tools/dbScripts/groupMembers.mysql, tools/dbScripts/households.mysql, tools/dbScripts/memberPermissions.mysql, tools/dbScripts/people.mysql, tools/dbScripts/questions.mysql, tools/dbScripts/roleMembers.mysql, tools/dbScripts/rolePermissions.mysql, tools/dbScripts/roles.mysql, tools/dbScripts/settings.mysql, tools/dbScripts/userChurches.mysql, tools/dbScripts/users.mysql, tools/dbScripts/visibilityPreferences.mysql
Need the edits here for a custom thank you message to be displayed on B1.
=> thanksMessage

src/controllers/GroupMemberController.ts, src/repositories/GroupMemberRepository.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/505
=> add: basic route for group members

src/controllers/UserController.ts, src/helpers/UserHelper.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/496
=> add: timestamp to forgot password links

src/controllers/UserController.ts
https://github.com/ChurchApps/ChurchAppsSupport/issues/547
=> add: timestamp to /login routes
